version: "3.8"

services:
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    command: npm run dev
    networks:
      - rt
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "3000:3000"

networks:
  rt: